infra:
  terraform-version: "1.4.9"
  working-path: terraform-aws

application:
  python-version: "3.13"
  working-path: app/src
  requirements: requirements.txt

tests:
  working-path: app/tests
  requirements: test-requirements.txt

environments:
  dev:
    role-arn: arn:aws:iam::123456789012:role/dev-lambda-role
    test:
      bob: nome
  prod:
    role-arn: arn:aws:iam::123456789012:role/prod-lambda-role
  files-to-replace:
    - app/src/config.py
    - app/src/another_config.py

# TODO: Add more options for the CI workflow, such as:
# quality:
#   lint: true
#   typecheck: true
#   test: true
#   coverage_threshold: 80
#   security_scan: true       # npm audit / pip-audit
