name: Deploy Dev

on:
  push:
    branches: [dev]
    paths:
      - "terraform-aws/**"
      - "app/**"

permissions:
  contents: read

jobs:
  cd:
    name: Deploy Lambda
    uses: SthoreH/shd-github-actions-workflows/.github/workflows/cd-lambda-python.yml@v1.4.1
    with:
      environment: dev
    secrets: inherit
